server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.81.210:3306/tutor?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: tutor
    password: tutor

# 日志配置
logging:
  level:
    root: info
    com.rjxy: debug
  file:
    name: log/blog-dev.log

# mybatis-plus 日志输出，查看sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl